README.md
dev/release.sh
pom.xml

Add support to run maven release prepare and publish
as well as the ability to publish snapshots

Add release script

---

src/main/java/com/ibm/cloudant/kafka/connect/CloudantSourceConnector.java

Source connector code to balance topics across tasks

Balance Topics

---

pom.xml
src/main/java/com/ibm/cloudant/kafka/common/InterfaceConst.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSinkTask.java

add a new attribute "kcschema" in the documents of the sink database with the schema of the SinkRecord when available

 #9 Add archive schema from SinkRecord in attribute kcschema

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CHANGES.md
CONTRIBUTING.md
DCO1.1.txt

*What*
Updated to DCO and added templates.
*How*
* Added CONTRIBUTING.md with DCO info.
* Added DCO1.1.txt.
* Added github templates for issues and PRs
* Added CHANGES.md
*Testing*
N/A - no code changes.

Dco contributing

---

CHANGES.md
build.gradle
src/main/java/com/ibm/cloudant/kafka/common/utils/JavaCloudantUtil.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSourceTask.java
src/test/java/com/ibm/cloudant/kafka/connect/utils/CloudantDbUtils.java
src/test/java/com/ibm/cloudant/kafka/performance/CloudantSinkPerformanceTest.java
src/test/java/com/ibm/cloudant/kafka/performance/CloudantSourceAndSinkPerformanceTest.java

Added the `UserAgentInterceptor` to the client build.
Consolidated methods that build CloudantClient so UA interceptor can be added in a single place.
Added `UserAgentInterceptor` initialization based on properties file.
Added gradle for property file generation for inclusion in jar.
No new automated tests, but validated the User-Agent header was as expected.
N/A

Added User-Agent interceptor and properties file

---

.travis.yml

Changed `.travis.yml` to use local docker `apache/couchdb`
CI passing.
N/A

Updated travis to use docker CouchDB

---

build.gradle

related to https://github.ibm.com/cloudant/integrations/issues/65
Email address `support@cloudant.com` has gone away and needs to be replaced.
Replace `support@cloudant.com` with `cldtsdks@us.ibm.com`.

Update support email address

---

.secrets.baseline
CHANGES.md
VERSION
build.gradle
src/main/java/com/ibm/cloudant/kafka/common/utils/JavaCloudantUtil.java
src/main/java/com/ibm/cloudant/kafka/common/utils/ResourceBundleUtil.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSinkConnector.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSinkConnectorConfig.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSinkTask.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSourceConnector.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSourceConnectorConfig.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSourceTask.java
src/test/java/com/ibm/cloudant/kafka/connect/utils/CloudantDbUtils.java

- Upgrade Kafka Connect to 3.1.0
- Update Scala to 2.12 since it's the minimum version for [Kafka 3.1.0 download](https://kafka.apache.org/downloads).
- Upgrade logging dependency to slf4j
fixes #52

Upgrade Kafka to 3.1.0

---

src/test/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSourceTaskTest.java

Replace `com.google.common.collect.Streams` instances with the built-in `java.util.stream.StreamSupport.stream`.
fixes #76

Remove use of com.google.common.collect.Streams

---

build.gradle
src/test/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSourceTaskTest.java

chore: remove org.json dependency

---

src/main/java/com/ibm/cloud/cloudant/kafka/common/utils/JavaCloudantUtil.java
src/main/java/com/ibm/cloud/cloudant/kafka/connect/SinkTask.java
src/main/java/com/ibm/cloud/cloudant/kafka/schema/SinkRecordToDocument.java
src/test/java/com/ibm/cloud/cloudant/kafka/schema/SinkRecordToDocumentTests.java

chore: refactor ConnectRecordMapper, rename to SinkRecordToDocument

---

src/main/java/com/ibm/cloud/cloudant/kafka/SinkConnector.java
src/main/java/com/ibm/cloud/cloudant/kafka/mappers/SinkRecordToDocument.java
src/main/java/com/ibm/cloud/cloudant/kafka/transforms/ArrayFlatten.java
src/main/java/com/ibm/cloud/cloudant/kafka/transforms/MapToStruct.java
src/main/java/com/ibm/cloud/cloudant/kafka/transforms/predicates/IsDesignDocument.java
src/main/java/com/ibm/cloud/cloudant/kafka/utils/JavaCloudantUtil.java
src/test/java/com/ibm/cloud/cloudant/kafka/SourceChangesConnectorTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/mappers/SinkRecordToDocumentTests.java
src/test/java/com/ibm/cloud/cloudant/kafka/performance/SinkPerformanceTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/tasks/SinkErrorTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/tasks/SourceChangesAndCloudantSinkTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/tasks/SourceChangesTaskTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/transforms/ArrayFlattenTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/transforms/MapToStructTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/utils/ServiceCallUtils.java
src/test/java/com/ibm/cloud/cloudant/kafka/validators/ValidationTest.java

Clean up remaining code warnings.
* `@SuppressWarnings("unchecked")` in places where we convert `Object` to our internally known types.
* Removed unused imports.
* Added type safety in some places.
- "No change"
- "No change"
- Modified existing tests because to remove warnings.
- "No change"

chore: cleanup warnings

---

Jenkinsfile
build.gradle

Generate and upload jar signature.
Fixes #122
* `build.gradle`
* Set env vars as appropriate project extra properties to configure signatory
* Add `onlyIf` to skip signing when no env vars set
* Add `signing` extension config for `jar` file
* `Jenkinsfile`
* Add env vars for signing creds
* Add additional upload for signature
- "No change"
- "No change"
- N/A build or packaging only changes - tested the following:
- gradle builds without env vars skip the signing task
- Jenkins build produces signature file
- gpg verified the generated signature
- "No change"

ci: sign the jar

---

docs/configuration-reference-changes-source.md
docs/connect-cloudant-sink-example.properties

also regenerate reference markdown files
fixes #128

docs: add DLQ and error options to sample sink properties

---

src/test/java/com/ibm/cloud/cloudant/kafka/tasks/SinceOptionTest.java

test fails because post changes options defaults have changed.

fix: failing test

---

src/main/java/com/ibm/cloud/cloudant/kafka/SourceChangesConnector.java
src/main/java/com/ibm/cloud/cloudant/kafka/tasks/SinkTask.java
src/main/java/com/ibm/cloud/cloudant/kafka/tasks/SourceChangesTask.java
src/main/java/com/ibm/cloud/cloudant/kafka/transforms/MapToStruct.java
src/main/java/com/ibm/cloud/cloudant/kafka/utils/JavaCloudantUtil.java

chore: Use parameterized logging where possible

---

.secrets.baseline
build.gradle

chore: update Cloudant java sdk to 0.4.0
Update version number
- "No change"
- "No change"
- "No change"

chore: update cloudant-java-sdk to 0.4.0

---

SECURITY.md

Add vulnerability reporting policy to the repo similar to one [added to java sdk](https://github.com/IBM/cloudant-java-sdk/pull/372)

Add vulnerability reporting policy

---

Jenkinsfile
build.gradle

This change adds SonarQube Analysis to our pipeline.
Introduced the `SonarQube analysis` stage.
- "No change"
- "No change"

build: add SonarQube analysis to pipeline

---

.secrets.baseline
CHANGES.md
build.gradle

Update `cloudant-java-sdk` to 0.4.3.
fixes #149

Update cloudant-java-sdk to 0.4.3

---

CHANGES.md
build.gradle

Update Kafka version to 3.4.0.
fixes #148

Update Kafka to 3.4.0

---

Jenkinsfile

Pipeline will fail from now on when any of our Quality Gate condition is not met.
Added `sonar.qualitygate.wait=true`, renamed the command `sonarqube` to `sonar` because `sonarqube` is deprecated.
- "No change"
- "No change"
- "No change"

build: wait for SQ quality gate is done

---

README.md
docs/releasing.md

Documentation only changes.
Add documents explaining release process for developers.
No change
No change
N/A
N/A

docs: add release process

---

.secrets.baseline
settings.gradle

If set use Artifactory for gradle plugins before falling back to Gradle plugins repo.
Add configuration to `settings.gradle`
- "No change"
- "No change"
- "No change"

i227 plugin deps

---

.github/dependabot.yml
.secrets.baseline
build.gradle
gradle/libs.versions.toml

Switch to a version catalog and enable dependabot.
* Move gradle dependencies to standard `gradle/libs.versions.toml` version catalog file and use bundles for dependency groups.
* Update `build.gradle` dependency references to use default version catalog `libs.` format.
* Add `.github/dependabot.yml`
- "No change"
- "No change"
- "No change"

Use version catalog and enable dependabot

---

Jenkinsfile

Simplify jar signing
Use an alternate executor without need for a separate signing container and writing of the config file.
- "No change"
- "No change"
- "No change"

build: simplify signing

---

Jenkinsfile

Adjust ci stage conditions for SQ
Fixes i493
Run SQ scans on PRs, exclude dependabot
- "No change"
- "No change"
- "No change"

ci: adjust SQ stage conditions
