IBM/cloudant-kafka-connector

pom.xml

MessageHub deploys Kafka 0.10.0.1 as base and we need a release of the connector that works for Kafka 0.10.0.1 (not 0.10.1.0)
This commit does 2 things:
- update our dependency from Kafka 0.10.1 to Kafka 0.10.0.1 (using a variable for the version dependency)
- change our .jar name to align with the Kafka version (using the same version variable)
As a result of this change we will build 
`kafka-connect-cloudant-0.10.0.1.jar`and `kafka-connect-cloudant-0.10.0.1-jar-with-dependencies.jar` accordingly
The branch should merge with `master` while we can break off a release for the (newer) version 0.10.1 already.

Upgrade to Kafka based on scala 2.11 and adjust our release name

---

README.md
pom.xml
src/main/java/com/ibm/cloudant/kafka/common/InterfaceConst.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSinkTask.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSinkTaskConfig.java
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSinkConnectorTest.java
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSinkTaskTest.java
src/test/resources/test.properties

Add a new parameter “replicate” in the file connect-cloudant-sink.properties. The property handle the schema of the objects in the sink database. The new attribute “replicate” handle and replace the attributes guid_schema and kafka_schema.
If the property true the source object should be mirrored in the sink database. Therefore, the system using the guid_schema from the source object and don’t add the kafka_schema to the object.
If the property false the source object should be saved with additional information in the sink database. Therefore, the system create a new object id from kafka (#8) and add the kafka_schema from the SinkRecord (#9).

Update: Add Parameter “replicate” for setting guid_schema and kafka_schema #23 

---

CHANGES.md
Jenkinsfile
README.md
build.gradle
src/main/java/com/ibm/cloudant/kafka/common/InterfaceConst.java
src/main/java/com/ibm/cloudant/kafka/common/MessageKey.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSourceConnectorConfig.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSourceTask.java
src/main/java/com/ibm/cloudant/kafka/schema/JsonStruct.java
src/main/resources/message_en_US.properties
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSinkConnectorTest.java
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSinkTaskTest.java
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSourceConnectorTest.java
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSourceTaskTest.java
src/test/java/com/ibm/cloudant/kafka/connect/utils/CloudantDbUtils.java
src/test/java/com/ibm/cloudant/kafka/connect/utils/ConnectorUtils.java
src/test/java/com/ibm/cloudant/kafka/performance/CloudantSinkPerformanceTest.java
src/test/java/com/ibm/cloudant/kafka/performance/CloudantSourceAndSinkPerformanceTest.java
src/test/java/com/ibm/cloudant/kafka/performance/CloudantSourcePerformanceTest.java
src/test/java/com/ibm/cloudant/kafka/schema/JsonStructTest.java
src/test/resources/schema_types.json
src/test/resources/test.properties

Added option to generate Struct schema with Cloudant doc messages.
* Reverted to non docker pipeline build (for build stability, unrelated to the schema change)
* Fixed incorrect test package name (`kakfa` -> `kafka` unrelated to this change)
* Added option for generating Struct schema for JSON docs
* Added config to default to existing behaviour, but allow setting of a property so message values have a generated Struct.
* Added constants and messages for above config.
* Added JsonStruct class for converting JsonObject to a Struct schema and building a Struct.
* Updated source task to output Struct when option enabled.
Added schema tests
* Default to cloudant.value.schema.struct=false for existing tests.
* …

Schema opts

---

src/main/java/com/ibm/cloudant/kafka/common/utils/JavaCloudantUtil.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSinkConnector.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSourceConnector.java

Updated connector reported version number
Stopped returning the Kafka version and instead use a constant initialized from the connector's own properties file generated at build time.
Checked output from built jar:
>[2018-03-15 13:52:07,402] INFO Instantiated connector cdt-kafka-example with version 0.100.0-SNAPSHOT-kafka-1.0.0 of type class com.ibm.cloudant.kafka.connect.CloudantSourceConnector (org.apache.kafka.connect.runtime.Worker:208)
N/A

Updated connector reported version number

---

.travis.yml
CHANGES.md
src/main/java/com/ibm/cloudant/kafka/common/utils/JavaCloudantUtil.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSourceTask.java
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSourceTaskTest.java

Stopped some configuration being shared between instances.
Some fields are configured per connector instance config and should not be `static` in `CloudantSourceTask`:
* `lastSequenceNumber`
* `batch_size`
* `cloudantDb`
Added
`com.ibm.cloudant.kafka.connect.CloudantSourceTaskTest#testMultipleConnectorInstances`
Fixes #39

Stopped fields being shared between configs

---

CHANGES.md
README.md

I fixed the README to align with the 2.8.0 Kafka version.
* `offset.storage.file.filename` and `bootstrap.servers` are now required properties in the `connect-standalone.properties` or `connect-distributed.properties` files, so I added them.
* I extended the commands with the `.sh` extension.
* `connect-log4j.properties` file takes place in the `$kafka_home/config` directory.
No change
No change
No tests. Actually I tested manually the README with the latest Kafka.
No change

Fix README

---

.secrets.baseline
CHANGES.md
build.gradle
src/main/java/com/ibm/cloudant/kafka/common/utils/JavaCloudantUtil.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSinkConnectorConfig.java
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSourceTask.java
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSinkConnectorTest.java
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSinkTaskTest.java
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSourceAndSinkTest.java
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSourceConnectorTest.java
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSourceTaskTest.java
src/test/java/com/ibm/cloudant/kafka/connect/utils/CloudantDbUtils.java
src/test/java/com/ibm/cloudant/kafka/connect/utils/ConnectorUtils.java
src/test/java/com/ibm/cloudant/kafka/performance/CloudantSinkPerformanceTest.java
src/test/java/com/ibm/cloudant/kafka/performance/CloudantSourceAndSinkPerformanceTest.java
src/test/java/com/ibm/cloudant/kafka/performance/CloudantSourcePerformanceTest.java

fixes #50
The underlying Cloudant client library is now EOL. This PR refactored the codebase and tests to use the new `cloudant-java-sdk` library. 
"No change"
Updated existing tests to use new library.
No new tests.

50 migrate to new sdk

---

Jenkinsfile
build.gradle

Fix publishing to use the new gradle model. NB this is now achieved by the `publish` task.
Remove and rewrite `uploadArchives` task per advice [here](https://docs.gradle.org/current/userguide/upgrading_version_5.html#legacy_publication_system_is_deprecated_and_replaced_with_the_publish_plugins)
No change
No change
Tested locally up to point of actually publishing assets, ie
```
./gradlew -i -Dsigning.secretKeyRingFile=/home/tomblench/.gnupg/secring.gpg -Dsigning.password=test -Dsigning.keyId=xxx -DossrhUsername=fake -DossrhPassword=fake clean publish
```
Observed that files are output to correct locations, and `publishMavenJavaPublicationToMavenRepository` step fails as expected `Received status code 401 from server: Unauthorized`.
No change

53: Fix publishing

---

.secrets.baseline
CHANGES.md
README.md
src/main/java/com/ibm/cloudant/kafka/connect/CloudantSinkTask.java
src/test/java/com/ibm/cloudant/kafka/connect/CloudantSourceAndSinkTest.java

Stop removing `_rev` from sink documents

---

.secrets.baseline
README.md
build.gradle
src/main/java/com/ibm/cloudant/kafka/schema/ConnectRecordMapper.java
src/test/java/com/ibm/cloudant/kafka/schema/ConnectRecordMapperTests.java

fixes #65 
- Modify the ConnectRecordMapper to check for the presence of a custom header on the record and use the value of that header as the ID.
- Use the HeaderFrom transform to convert a key to the header, avoiding the need for us to have any custom SMT.
- Add README section for using SMTs to rename, replace, or filter out `_id` field.  Also document how to remove tombstone records.
"No change"
"No change"
"No change"
For reviewers:
- [This example](https://github.com/IBM/cloudant-kafka-connector/compare/65-sink-id-transform?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R73-R80) requires a conditional SMT to drop the field if `_id == null`.  I need to re-review the SMT docs to see if we can filter on the value of fields.
- I've yet to successfully test …

Document the use of SMTs to customize _id field

---

src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSourceConnector.java

Previously we were returning `n` task configs for `tasks.max`, which was resulting in `n` copies of the event being written to kafka per cloudant document.
Fixes #7

fix: Only support 1 task in source connector

---

CHANGES.md
README.md
src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSourceTask.java
src/test/java/com/ibm/cloud/cloudant/kafka/connect/ClientManagerUtils.java
src/test/java/com/ibm/cloud/cloudant/kafka/connect/TombstoneTest.java

**Documentation**
Update README and CHANGES
**Testing**
Tested locally by deleting document from Cloudant and observing event with `./bin/kafka-console-consumer.sh  --bootstrap-server localhost:9092 --topic kafka_test --from-beginning --property print.key=true` 
```
{"schema":{"type":"string","optional":false},"payload":"f576db6ebceafaa4d585fa45bd8a3e1e"}	{
"_deleted": true,
"_id": "f576db6ebceafaa4d585fa45bd8a3e1e",
"_rev": "2-30dc7747c854572ca4d0a2f8e6497ffb"
}
{"schema":{"type":"string","optional":false},"payload":"f576db6ebceafaa4d585fa45bd8a3e1e"}	null
```

feat: Emit tombstones for deleted documents

---

src/main/java/com/ibm/cloud/cloudant/kafka/common/utils/JavaCloudantUtil.java
src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java
src/test/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkErrorTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTaskTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/connect/TombstoneTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/connect/utils/ServiceCallUtils.java

Handle errors in sink connector arising from posting to bulk_docs endpoint:
- Individual errors in batch response are reported to the error reporter, if present. This allows the original events to be sent to a DLQ and/or logged according to standard kafka config
- For more serious network/HTTP errors, throw an exception. This will ensure that the offsets are not committed and the event can be retried.
Additionally:
- Break up calls to bulk_docs into batches to avoid large request bodies
- Add tests for error handling
Fixes #84

84 handle per event errors

---

.github/dco.yml

Add DCO config to bypass DCO check for members.
```
require:
members: false
```
Stops the DCO bot from expecting a sign-off on commits that are _verified_ as coming from a member. This means the commits must be cryptographically signed.
- "No change"
- "No change"
- "No change"

chore: exclude members from DCO check

---

src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSourceTask.java

- `while (!stop.get())` logic was faulty since the loop will always be exited with 0 changes, some changes, or null.
- `_running` and `stop` variables not needed: if connector is removed or shutdown using the connect REST api, then `stop` will be called on the same thread as `poll`. Therefore these methods can be considered fully synchronous and there is no such thing as an "in flight" or "pending" request to cloudant. This was observed in both standalone and distributed configuration.
- Narrow scope of `cloudantChangesResult` by moving to local variable.
Fixes #94

fix: remove _running/stop machinery

---

src/main/java/com/ibm/cloud/cloudant/kafka/common/InterfaceConst.java
src/main/java/com/ibm/cloud/cloudant/kafka/common/MessageKey.java
src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkConnectorConfig.java
src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java
src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTaskConfig.java
src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSourceConnectorConfig.java
src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSourceTask.java
src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSourceTaskConfig.java
src/main/resources/message_en_US.properties
src/test/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTaskTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSourceConnectorTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/connect/utils/ConnectorUtils.java
src/test/java/com/ibm/cloud/cloudant/kafka/performance/CloudantSinkPerformanceTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/performance/CloudantSourceAndSinkPerformanceTest.java

- Move batch size options into source and sink config def
- Range validation and documentation for source and sink batch size
- Cleanup some unused config constants and properties
fixes #103

feat: batch size limits in options

---

src/main/java/com/ibm/cloud/cloudant/kafka/tasks/ConnectorConfig.java
src/main/java/com/ibm/cloud/cloudant/kafka/tasks/SinkConnectorConfig.java
src/main/java/com/ibm/cloud/cloudant/kafka/tasks/SourceChangesConnectorConfig.java
src/main/java/com/ibm/cloud/cloudant/kafka/validators/ListRecommender.java
src/main/java/com/ibm/cloud/cloudant/kafka/validators/UrlValidator.java
src/main/resources/message_en_US.properties

fixes #111
Open questions (see output below for reference):
- Is importance level correct for each?
- Is order correct?
- Do batch size, topics and starting sequence belong under "database" group?
Here is the RST output for the Sink Connector:
```
Database
^^^^^^^^
``cloudant.url``
Cloudant database connection URL (eg https://<uuid>.cloudantnosqldb.appdomain.cloud)
* Type: string
* Valid Values: <any URL>
* Importance: high
``cloudant.db``
Cloudant database name (for sink connector it will be created if it does not exist)
* Type: string
* Importance: high
``batch.size``
Size of batches to send to Cloudant _bulk_docs endpoint
* Type: int
* Default: 1000
* Valid Values: [1,...,20000]
* Importance: medium
``topics``
Kafka topic list
* Type: list
* Importance: high
Authentication …
```

chore: tidy up ConfigDef to aid README generation

---

src/main/java/com/ibm/cloud/cloudant/kafka/mappers/DocumentToSourceRecord.java
src/main/java/com/ibm/cloud/cloudant/kafka/utils/NumberSafeMap.java
src/test/java/com/ibm/cloud/cloudant/kafka/mappers/DocumentHelpers.java
src/test/java/com/ibm/cloud/cloudant/kafka/utils/NumberSafeMapTest.java

Convert GSON's LazilyParsedNumbers into specific Number types so that they are compatible with Kafka converters.
Fixes #112 
Change the `DocumentToSourceRecord` mapper to use a new `NumberSafeMap` that converts instances of `Number` into the narrowest possible type.
There is a concious decision here to not just use `Long` or `Double` to maintain the widest possible compatibility with Kafka connect types (e.g. `Int8`, `Int16` etc). It is easier to accept narrower values into wider ones (e.g. `Int8` -> `Int32` than it is to do the opposite).
There is additional detail about the behaviour in the javadoc of the `NumberSafeMap` class.
Currently the type of last resort is `double` - I am awaiting validation from CouchDB that this is in fact the highest precision available in the source JSON …

fix: convert LazilyParsedNumbers to specific Number types

---

src/main/java/com/ibm/cloud/cloudant/kafka/tasks/SourceChangesTask.java
src/test/java/com/ibm/cloud/cloudant/kafka/tasks/SourceChangesTaskTest.java

Refactor source partiton offset map.
Fixes #107
Replace the concatenated string offset with a Map containing two entries, one for the URL and one for the DB.
Re-use the existing constants for `cloudant.url` and `cloudant.db` as keys.
Remove unnecessary `offset` method and populate the `sourcePartition` map during `start`.
- Internal change to offset Map format, no external change.
- "No change"
- Added new test `SourceChangesTaskTest#testSourcePartitionAndOffsetMaps()` to validate correct partition and offset entries.
- "No change"

refactor: source partition offset map

---

src/main/java/com/ibm/cloud/cloudant/kafka/mappers/SinkRecordToDocument.java
src/test/java/com/ibm/cloud/cloudant/kafka/mappers/SinkRecordToDocumentTests.java

fixes #116
NB original issue was incorrect, nested structs are handled (see `testConvertComplexStruct`), but collection/list/array types were not always correctly handled.

fix: ensure collection (array/list) types are converted properly

---

src/main/java/com/ibm/cloud/cloudant/kafka/tasks/SourceChangesConnectorConfig.java
src/main/java/com/ibm/cloud/cloudant/kafka/tasks/SourceChangesTask.java
src/main/resources/message_en_US.properties
src/test/java/com/ibm/cloud/cloudant/kafka/tasks/SinceOptionTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/tasks/TombstoneTest.java

fix: change `cloudant.since` logic to prefer saved offset, if present

---

README.md
src/main/java/com/ibm/cloud/cloudant/kafka/mappers/DocumentToSourceRecord.java
src/main/java/com/ibm/cloud/cloudant/kafka/transforms/predicates/IsDesignDocument.java
src/main/java/com/ibm/cloud/cloudant/kafka/utils/MessageKey.java
src/main/resources/message_en_US.properties
src/test/java/com/ibm/cloud/cloudant/kafka/tasks/TombstoneTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/transforms/predicates/IsDesignDocumentTest.java

fixes #135
testing showing new key output:
```sh
./bin/kafka-console-consumer.sh  --topic kafka_test_topic --bootstrap-server localhost:9092  --from-beginning --property print.key=true
...
{"_id":"4826c5d0c7c9eba0babc7a17699405af","cloudant.url":"https://740f610a-33d2-40bd-8f6b-2d4ef06c2140-bluemix.cloudantnosqldb.appdomain.cloud","cloudant.db":"cloudant_source_kafka_test_db"}	{"_rev":"1-967a00dff5e02add41819138abb3284d","_id":"4826c5d0c7c9eba0babc7a17699405af"}
```

feat: change record key to struct including url and db

---

Jenkinsfile
build.gradle

Package as a zip instead of an "uber jar".
The "uber jar" failed to include all content from bundled dependencies because of path clashes. It is better to packge a directory so the dependencies can remain in their own jars.
This is achieved by using the gradle `distribution` plugin and creating a zip file.
- Change in installation method.
- "No change"
- N/A build or packaging only changes, but did verify new output content, signature and function.
- "No change"

build: package as zip instead of jar

---

CHANGES.md
src/main/java/com/ibm/cloud/cloudant/kafka/tasks/SourceChangesTask.java
src/main/java/com/ibm/cloud/cloudant/kafka/utils/JavaCloudantUtil.java
src/main/java/com/ibm/cloud/cloudant/kafka/utils/NumberSafeMap.java
src/test/java/com/ibm/cloud/cloudant/kafka/SourceChangesConnectorTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/tasks/SinkTaskTest.java
src/test/java/com/ibm/cloud/cloudant/kafka/utils/NumberSafeMapTest.java

Fixes some bugs and blocker code smells. Also introduces a new behavior for throwing an error when database could not be created.
I have filled one empty test (`SourceChangesConnectorTest .testStop`) body with a presumably useful test.
I also changed `new BigDecimal(...)` to `BigDecimal.valueOf(...)` in `NumberSafeMapTest` to pass the tests for the modified `NumberSafeMap` class.
Other modifications were previously discussed online or highlighted in the SQ report.
Stop sink connector on target database creation failure.
Need to be careful about printing out the stack trace in the future.
As previously mentioned, mainly refactor happened in the tests, and filled one test with a body.
- "No change"

Fix sq issues

---

README.md

Release instructions were removed in #173, but a reference to that document was left in the README.
This PR removes the section with the reference to the release doc from the readme.
- "No change"
- "No change"
- "No change"

docs: remove release process from README
